# Generated by Django 3.1.6 on 2021-02-08 16:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_released', models.DateField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeoCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('datetime_rating', models.DateTimeField()),
                ('review_title', models.CharField(blank=True, max_length=250, null=True)),
                ('review_content', models.TextField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_music_app.album')),
                ('user', models.ForeignKey(on_delete=models.SET('unknown[`]'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('webshop', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.ForeignKey(on_delete=models.SET('unknown'), to='rate_music_app.geocountry')),
            ],
        ),
        migrations.CreateModel(
            name='GeoCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('city_ascii', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=13)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=13)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_music_app.geocountry')),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_formed', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('links', models.CharField(blank=True, max_length=100, null=True)),
                ('band_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('band_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=models.SET('unknown'), to='rate_music_app.geocity')),
                ('country', models.ForeignKey(on_delete=models.SET('unknown'), to='rate_music_app.geocountry')),
                ('gender', models.ManyToManyField(to='rate_music_app.Gender')),
                ('label_current', models.ForeignKey(blank=True, null=True, on_delete=models.SET('unknown'), to='rate_music_app.label')),
                ('labels_past', models.ManyToManyField(blank=True, null=True, related_name='band_past_labels', to='rate_music_app.Label')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_music_app.band'),
        ),
        migrations.AddField(
            model_name='album',
            name='band_split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_second_band', to='rate_music_app.band'),
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('unknown'), to='rate_music_app.label'),
        ),
    ]
